version: "2"

linters:
  default: standard
  enable:
    - dupl
    - gocyclo
    - gocognit
    - maintidx

  settings:
    dupl:
      threshold: 100
    gocyclo:
      min-complexity: 15
    gocognit:
      min-complexity: 15
    maintidx:
      under: 20

  exclusions:
    generated: strict
    paths:
      - '.*\.gen\.go$'

output:
  formats:
    github-actions:
      path: stdout
    sarif:
      path: golangci-lint.sarif

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
